# Generated by Django 3.2.25 on 2025-11-08 20:02

import checkout.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_confirmation_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=checkout.models.default_expiry_date)),
                ('active', models.BooleanField(default=True)),
                ('one_time_use', models.BooleanField(default=True)),
            ],
        ),
    ]
