# Generated by Django 3.2.25 on 2025-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
