# Generated by Django 4.2.24 on 2025-09-12 15:47
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default='placeholder',
                max_length=255,
                null=True,
                verbose_name='image',
            ),
        ),
    ]