# Generated by Django 3.2.25 on 2025-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_filename',
            field=models.CharField(blank=True, help_text="Filename under static/images/, e.g. 'pistachio-cake.jpg'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional remote image URL.', max_length=500, null=True),
        ),
    ]
